#!/bin/sh
#author Yuryev Denis
#site ne-ne-ne.ru
NAME=transmission-daemon
CONFFILE=/root/.config/transmission-daemon
case "$1" in
        start)
                echo -n "Starting transmission.."
                if [ -n "`pidof $NAME`" ]; then
                        echo ""
                        exit
                fi
                if [ "$ENABLE_DAEMON" = "0" ]; then
                        echo "Error: Daemon disabled!"
                        exit
                else [ "$ENABLE_DAEMON" = "1" ]
                        $NAME -g $CONFFILE
                fi
                echo "OK!"
        ;;
        stop)
                echo -n "Stopping transmission-daemon.."
                if [ "$ENABLE_DAEMON" = "0" ]; then
                        echo "Error: Daemon disabled!"
                        exit
                fi
                killall $NAME
                echo "OK!"
        ;;
        restart)
                echo -n "Restarting transmission-daemon.."
                killall $NAME
                sleep 2
                if [ "$ENABLE_DAEMON" = "0" ]; then
                        echo "Error: Daemon disabled!"
                        exit
                fi
                $NAME -g $CONFFILE
                echo "OK!"
        ;;
*)
echo "Usage: /opt/etc/init.d/$NAME {start|stop|restart}"
exit 1
;;
esac

exit 0
